// client/src/App.jsx
import React from 'react';
import Header from './components/Header';
import CameraContainer from './components/CameraContainer';
import FileContainer from './components/FileContainer';

import 'bootstrap/dist/css/bootstrap.min.css';
import './app.css';

const App = () => {
    return (
        <div className="container-fluid">
            <Header />
            <div className="main">
                <CameraContainer />
                <FileContainer />
            </div>
        </div>
    );
}
export default App;

// client/src/App.vue
<template>
  <div id="app" class="container-fluid">
      <Header />
    <CameraContainer/>
  </div>
</template>

<script>
import CameraContainer from './components/CameraContainer.vue'
import Header from './components/Header';

export default {
  name: 'app',
  components: {
    CameraContainer,
    Header
  }
}
</script>
