// client/src/components/Camera.jsx
import React from 'react';

const Camera = ({camera}) => {
    return (
        <div className="card cam_card">
            <div className="card-header">
                <p className="float-left">{camera.name}</p>
                <p className="float-right">
                    status:
                </p>
            </div>
            <img src="stream_url" alt="video" className="cam-feed media-object"/>
            <div className="card-footer"></div>
        </div>
    );
}


export default Camera;

// client/src/components/Camera.vue
<template>
  <div class="col-md-7">
    <div class="card">
      <div class="card-header">
        <p>Camera:</p>
      </div>
      <img
        class="cam-feed media-object"
        :src="stream"
        alt="video"
        height="320"
        width="426"
      />
      <div class="card-footer">
        <p v-if="isRecording">Camera is recording</p>
        <p v-else>Currently not recording</p>
      </div>
    </div>
  </div>
</template>

<script>
import { fetcher, serverUrl } from '../logic/fetchWrapper';

export default {
  name: 'Camera',
  created() {
    setInterval(this.getCamStatus, 3000);
  },
  data() {
    return {
      isRecording: false,
    }
  },
  props: ['stream'],
  methods: {
    getCamStatus() {
      fetcher('/camStatus')
        .then(res => res.text())
        .then(text => {
          this.isRecording = text === 'true';
        });
    }
  }
}
</script>
<style scoped>
img.cam-feed {
  margin: 0 auto;
}
</style>
