// client/src/components/VideoPlayer.jsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons';

const VideoPlayer = ({ video, clipName }) => {
    return (
        <div className="col-md-6 col-sm-6 col-xs-6">
            <div className="card">
                <div className="card-header">
                    <p>Previous footage: {clipName}</p>
                </div>
                <video
                    src={video}
                    autoplay
                    controls
                    preload="metadata" alt="video"
                    className="media-object"></video>
            </div>
            <button className="btn btn-secondary go-back">
                <FontAwesomeIcon icon={faArrowLeft} />Live
            </button>
        </div>
    );
}

export default VideoPlayer;

// client/src/components/VideoPlayer.vue
<template>
  <div class="col-md-7">
    <div class="card">
      <div class="card-header">
        <p>Previous footage: {{clipName}}</p>
      </div>
      <video
        class="media-object"
        :src="video"
        autoplay
        controls
        preload="metadata"
        alt="video"
        height="320"
        width="426"
      />
    </div>
    <button class="btn btn-secondary go_back" v-on:click="backToFeed"><font-awesome-icon icon="arrow-left"/>Live</button>
  </div>
</template>

<script>

export default {
  name: 'VideoPlayer',
  props: ['video','clipName'],
  methods: {
      backToFeed() {
          this.$emit('backToLiveFeed')
      }
  }
}
</script>
<style scoped>
video {
  margin: 0 auto;
}

button.go_back {
    margin-top: 0.5em;
}
button.go_back > svg {
    margin: 0 5px 0 0;
}
</style>
